version: "3"
services:
  gacha-cron:
    image: commojun/cron:latest
    restart: always
    environment:
      CRONTAB_FILE: /cron/crontab
    volumes:
      - $PWD/cron/:/cron/
      - /root/suna/:/root/suna/
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  web:
    image: nginx:alpine-slim
    restart: always
    volumes:
      - /root/suna/public:/usr/share/nginx/html:ro
    ports:
      - '8056:80'
    logging:
      options:
        max-size: "10m"
        max-file: "3"
