version: "3"
services:
  gacha-cron:
    image: commojun/cron:latest
    restart: always
    environment:
      CRONTAB_FILE: /cron/crontab
    volumes:
      - $PWD/cron/:/cron/
      - /root/suna/:/root/suna/
    logging:
      options:
        max-size: "10m"
        max-file: "3"
